# Generated by Django 2.2.5 on 2019-12-27 05:25

from django.db import migrations, models
import taskmanager_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FilePathField(path=taskmanager_app.models.images_path)),
                ('end_date', models.DateField()),
                ('author', models.ForeignKey(on_delete='models.CASCADE', to='taskmanager_app.User')),
            ],
        ),
    ]
