# Generated by Django 2.2.5 on 2019-12-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0003_auto_20191228_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
